### ISSUE TITLE
Logging - invalid format?

### ISSUE THREAD

**Issue by karpikpl** [Avanade/Liquid-Application-Framework#100]
Question about logging - it doesn't look like it's configured correctly out of the box when using templates.

Log messages are with placeholders e.g. `{ContentType}`
```
{"EventId":2,"LogLevel":"Debug","Category":"Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector","Message":"Selected output formatter \u0027Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter\u0027 and content type \u0027application/json\u0027 to write the response.","State":{"Message":"Selected output formatter \u0027Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter\u0027 and content type \u0027application/json\u0027 to write the response.","OutputFormatter":"Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter","ContentType":"application/json","{OriginalFormat}":"Selected output formatter \u0027{OutputFormatter}\u0027 and content type \u0027{ContentType}\u0027 to write the response."}}
```

**Comment by fructuoso** [comment]
@karpikpl can you explain this problem? Can paste your sample code here?

**Comment by karpikpl** [comment]
I think I miss-interpreted how it's supposed to work...
I got it on the out-of-the-box sample, and it had this `\u0027{OutputFormatter}\u0027 and content type \u0027{ContentType}\u0027 to write the response.` which I think is expected, since it logs the message and the "format" of the message.

It was just little hard to read from console.

**Comment by jvreichert** [comment]
This bug no longer exists, in some tests performed, the log no longer has any problems

`{"@timestamp":"2023-03-22T14:38:06.7596942-03:00","log.level":"Error","message":"Unexpected error: System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler 2[Liquid.Arch.Demo.Application.Handlers.V1.Data.SearchData.SearchDataRequest,Liquid.Arch.Demo.Application.Handlers.V1.Data.SearchData.SearchDataResponse]. Register your handlers with the container. `
