### ISSUE TITLE
How to add validation to AddGenericEntityCommand

### ISSUE THREAD

**Issue by karpikpl** [Avanade/Liquid-Application-Framework#101]
It's possible to override`AddGenericEntityCommand`, but it's not clear how to add validation.

adding this class:
```csharp
class PostMyObjectCommandValidator : AbstractValidator<AddGenericEntityCommand<MyObjectEntity, int>>
    {
        public PostMyObjectCommandValidator()
        {
            RuleFor(request => request.Data.Id).Empty().Null();
            RuleFor(request => request.Data.Age).NotEmpty().NotNull().GreaterThan(0);
            RuleFor(request => request.Data.Name).NotEmpty().NotNull();
        }
    }
```

didn't work

**Comment by fructuoso** [comment]
You need implement **AddGenericEntityCommandValidator** and must be set class to public.

**Comment by karpikpl** [comment]
ok thanks.
Making it public worked.

I'm not sure why template creates non-public validators though
```csharp
using FluentValidation;

namespace MyProject.Domain.Handlers.MyObject.Put
{
    class PutMyObjectCommandValidator : AbstractValidator<PutMyObjectCommand>
    {
        public PutMyObjectCommandValidator()
        {
            RuleFor(request => request.Body.Id).NotEmpty().NotNull();
        }
    }
}
```

see: https://github.com/Avanade/Liquid-Application-Framework/blob/c2663d5c002999ad36ee29d85d7f0a312d1b61de/templates/src/Liquid.Templates/Templates/Liquid.Domain.AddHandler/PROJECTNAME.Domain/Handlers/ENTITYNAME/COMMANDNAME/COMMANDNAMEENTITYNAMECommandValidator.cs#L5

so all validators need to be public?

**Comment by fructuoso** [comment]
This happens because the validators are injected by another project, if they are not public they will not be found.

In your case, they has been injected in WebApi project.

**Comment by karpikpl** [comment]
hmm ok...
so that means the template is OK but I didn't use it correctly?

I followed following steps:
1. use template to generate domain and webapi
2. validation works - validators are not generated public
3. swap controller implementation with `GenericCrudController` and update validator to handle `AddGenericEntityCommand`
4. validator no longer works because it's not public

and this is all fine and by design?

**Comment by fructuoso** [comment]
Which template you are using?

This validation class has been created by the template?

If you are using CRUD Extension, you can implement validation like that https://github.com/fructuoso/LiquidCRUDExample/blob/main/src/Domain/Commands/AddProduct/AddProductCommandValidator.cs

**Comment by fructuoso** [comment]
I has clicked in your Link, it is a Issue.

I will reopen this issue.
