### ISSUE TITLE
PACKAGENAME isn't a parameter of template

### ISSUE THREAD

**Issue by fructuoso** [Avanade/Liquid-Application-Framework#103]
When create a new project using a template the swagger show PACKAGENAME, but PACKAGENAME isn't a parameter of template.

We could be replace this value to PROJECTNAME?

![image](https://user-images.githubusercontent.com/2004713/155857371-2504f1df-13a0-4b71-a6ee-297fa2bb1f16.png)

**Comment by lucianareginalino** [comment]
Yes, should be "PROJECTNAME".
