### ISSUE TITLE
How to subscribe to service bus topic?

### ISSUE THREAD

**Issue by karpikpl** [Avanade/Liquid-Application-Framework#107]
Looks like there are only 2 settings available:
```json
    "messaging": {
      "serviceBus": {
        "PropertyConsumer": {
          "ConnectionString": "",
          "EntityPath": "properties.consumer"
        }
      }
```

is format `[Topic]/[Subscription]` supported?

**Comment by karpikpl** [comment]
also I don't get any exception or events regardless if I set invalid (`"EntityPath": "foo"`) or valid EntityPath in my configuration

```csharp
 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddLiquidConfiguration();

                    services.AddLiquidServiceBusConsumer<HotelWorker, HotelCdc>("Liquid:messaging:serviceBus:PropertyConsumer", true, typeof(HotelWorker).Assembly);
                });
    }
```

**Comment by fructuoso** [comment]
@karpikpl in ServiceBus standard entitypath is:

**To Read:**
* "Topic/Subscriptions/Subscription"
* "Queue"

**To write:**
* "Topic"
* "Queue"

**Comment by karpikpl** [comment]
I still think this is both undocumented and invalid behavior, because no exception is thrown when invalid `entitypath` is provided
