### ISSUE TITLE
DataverseAdapter enhancements

### ISSUE THREAD

**Issue by rochamarcos** [Avanade/Liquid-Application-Framework#202]
Proposed improvements:

1. Enable the DataverseAdapter to use the following parameters in OrganizationRequests:

- IgnoreCustomPluginExecution
- SuppressCallbackRegistrationExpanderJob
- Suppress duplicate detection

2. Enable the DataverseAdapter to consider optimistic concurrency on DeleteRequest and UpdateRequest.

**Comment by lucianareginalino** [comment]
solved by #203
