### ISSUE TITLE
Simplify Liquid.WebApi.Http dependency injection

### ISSUE THREAD

**Issue by lucianareginalino** [Avanade/Liquid-Application-Framework#47]
For inject all dependencies needed to use Liquid.WebApi.Http, is necessary call four methods as exemplified below:

```C#
 //Liquid WebApi Injection
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddAutoMapper(typeof(MySampleQuery).Assembly);
            services.ConfigureLiquidHttp();
            services.AddDomainRequestHandlers(GetType().Assembly);
```

In order to keep the Liquid an intuitive framework, the injection of the components should be more intuitive to.

**Comment by aledaccas** [comment]
The only method that can be added to ConfigureLiquidHttp is the services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
Others are fine tunning optional methods.
