### ISSUE TITLE
How does translation (Localization) work?

### ISSUE THREAD

**Issue by chcm15** [Avanade/Liquid-Application-Framework#58]
I saw that several "Localization" methods are deprecated. Should I look for a solution outside the framework?

**Comment by lucianareginalino** [comment]
Hi @Passarimm , thanks for the issue.

We plan to refactor this feature and this will likely generate breaking changes , so, to avoid them, we suggest to use aspnetcore native features :

https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/localization?view=aspnetcore-5.0

**Comment by chcm15** [comment]
> Hi @Passarimm , thanks for the issue.
> 
> We plan to refactor this feature and this will likely generate breaking changes , so, to avoid them, we suggest to use aspnetcore native features :
> 
> https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/localization?view=aspnetcore-5.0

Thanks! =)
