### ISSUE TITLE
Configuração do Liquid.Services

### ISSUE THREAD

**Issue by chcm15** [Avanade/Liquid-Application-Framework#59]
Olá pessoal!

Antes de mais nada, parabéns pelo trabalho. Este framework foi uma excelente iniciativa de vocês!

Estou criando um projeto conceito com a utilização do Liquid ( https://github.com/Passarimm/LiquidPOC ). O objetivo é implementar tudo o que o framework oferece da melhor forma possível (imagino que eu ainda esteja um pouco longe disso, mas chego lá... rsrs).   Qualquer ajuda será bem vinda.

Agora queria tirar uma dúvida....

Estou com problemas para configurar o Liquid.Services.

O exemplo da página https://github.com/Avanade/Liquid.Services está correto? Parece que houve uma alteração do parâmetro do tipo ILightConfiguration para ILightServiceConfiguration. Qual a configuração necessária para injetar essas dependências corretamente?

**Comment by lucianareginalino** [comment]
Olá Passarim! bom dia!

Ficamos felizes que esteja adotando o uso, e que esteja gostando!

Sobre sua questão, o Liquid.Core passou por uma reformulação sobre vários pontos, e estou trabalhando na adaptação dos componentes para o novo modelo. Este componente Liquid.Services ainda não passou por esta migração, então pode ter pontos quebrados, especificamente a parte de configuração, está defasada em relação a versão estável do Liquid.Core.

A versão estável deste componente, bem como dos outros que ainda não foram publicados, será lançada até quarta-feira 25/08, com documentação atualizada.

vou manter este issue aberto, para documentar o impacto que você está tendo, e fico à disposição caso tenha mais dúvidas.

**Comment by chcm15** [comment]
Opa! Tudo bem!

Aguardo a nova versão.
