### ISSUE TITLE
HTTP Status code for Unauthorized and Forbbiden - ExceptionCustomCodes

### ISSUE THREAD

**Issue by rodrigogfreire** [Avanade/Liquid-Application-Framework#62]
Hey guys, first of all, congratulations for this amazing framework.

If you allow me I have a small suggestion, in the file "ExceptionCustomCodes.cs" the http response code for Unauthorized and Forbbiden both are returning 400 status code, and it will be better return status 401 and 403 respectively.

I sent the fix for your appreciation
https://github.com/Avanade/Liquid.Core/pull/26

Thank you for your time,

**Comment by lucianareginalino** [comment]
Hi, can you please reopen your pull request to merge your code into "release-v2.0.1" branch instead of main branch ?

regards.

**Comment by rodrigogfreire** [comment]
Yes! Done --> https://github.com/Avanade/Liquid.Core/pull/27
:)
