### ISSUE TITLE
Restructure Liquid repositories to use a single approach, monorepo or multirepo, not both

### ISSUE THREAD

**Issue by ycamargo** [Avanade/Liquid-Application-Framework#81]
Nowadays, Liquid repositories are structured in both ways, using a multirepo approach for components (Core, Repository, Messaging, WebApi, etc) but, inside those repos, Liquid uses a monorepo approach for base classes and cartridges.
That is causing some confusion on dependencies as well. Cross-repository dependencies are done by references to Nuget packages and intra-repository dependencies are done by project references inside the VS Solution.
We should use a single approach.

Going to a full multirepo:
- create separate repositories for each component that has its own lifecycle;
- establish all dependencies based on Nuget packages;
- this will demand a lot of repositories and, probably, will be very hard to operate and maintain;

Going to a full monorepo:
- migrate all code from other repos to Liquid-Application-Framework repository;
- also, establish all dependencies based on Nuget packages (recommended);
- this will demand, probably, more complex CI/CD yaml files, but will make the operation and issue management easier;

**Comment by lucianareginalino** [comment]
We decided to go for the monorepo approach, mainly to make managing the product easier. The code migration has already been carried out and the CI/CD workflows have been refactored and are functional.
